apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculate-app-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          - path: /((?!api).*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: 80
