name: Checks

on:
  workflow_dispatch:  
  push:
    branches: [main]

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: calculate-app

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Check linting
              run: npm run lint
              
            - name: Run tests
              run: npm test
            
    push-ecr:
        runs-on: ubuntu-latest
        needs: checks
        permissions:
            id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build, tag, and push docker image to Amazon ECR
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: ${{ env.ECR_REPOSITORY }}
                IMAGE_TAG: ${{ github.sha }}
              run: |
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    deploy:
      needs: push-ecr
      permissions:
            id-token: write
      uses: "./.github/workflows/deploy.yaml"
      with:
        commit-id: ${{ github.sha }}
        deployment-name: "calculate-app-fe"
        chart-file-directory: "./helm"
        values-file: "./helm/values-dev.yaml"
      secrets:
        AWS_ROLE_ARN: ${{ secrets.EKS_ROLE_ARN }}
        EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}              
            