name: Test EKS Deployment

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.EKS_ROLE_ARN }}
          aws-region: eu-north-1
        
      - name: Verify AWS credentials
        run: aws sts get-caller-identity  

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.0'
      
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region eu-north-1 --name modular-eks --kubeconfig ./kubeconfig
      

      - run: cat ./kubeconfig
        env:
          KUBECONFIG: ./kubeconfig
      
      - name: Check ConfigMap
        run: |
          kubectl get configmap aws-auth -n kube-system -o yaml
        env:
          KUBECONFIG: ./kubeconfig    

      - run:  |
            export KUBECONFIG=./kubeconfig
            kubectl get svc --v=8

    